name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        run: curl -X POST -d {} ${{ secrets.DEPLOY_HOOK }}
